/**
 * Database Types
 * 
 * TypeScript types for Supabase database schema
 */

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          username: string | null;
          full_name: string | null;
          avatar_url: string | null;
          subscription_tier: 'free' | 'starter' | 'pro' | 'business';
          subscription_status: 'active' | 'inactive' | 'cancelled' | 'past_due';
          monthly_ai_credits: number;
          ai_credits_used: number;
          total_sites_created: number;
          max_sites_allowed: number;
          stripe_customer_id: string | null;
          stripe_subscription_id: string | null;
          metadata: any;
          created_at: string;
          updated_at: string;
          last_login_at: string | null;
        };
        Insert: {
          id: string;
          email: string;
          username?: string | null;
          full_name?: string | null;
          avatar_url?: string | null;
          subscription_tier?: 'free' | 'starter' | 'pro' | 'business';
          subscription_status?: 'active' | 'inactive' | 'cancelled' | 'past_due';
          monthly_ai_credits?: number;
          ai_credits_used?: number;
          total_sites_created?: number;
          max_sites_allowed?: number;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          metadata?: any;
          created_at?: string;
          updated_at?: string;
          last_login_at?: string | null;
        };
        Update: {
          id?: string;
          email?: string;
          username?: string | null;
          full_name?: string | null;
          avatar_url?: string | null;
          subscription_tier?: 'free' | 'starter' | 'pro' | 'business';
          subscription_status?: 'active' | 'inactive' | 'cancelled' | 'past_due';
          monthly_ai_credits?: number;
          ai_credits_used?: number;
          total_sites_created?: number;
          max_sites_allowed?: number;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          metadata?: any;
          created_at?: string;
          updated_at?: string;
          last_login_at?: string | null;
        };
      };
      sites: {
        Row: {
          id: string;
          user_id: string | null;
          name: string;
          slug: string;
          description: string | null;
          status: 'draft' | 'published' | 'archived';
          template_id: string | null;
          components: any;
          theme: any;
          seo_metadata: any;
          deployment_url: string | null;
          preview_url: string | null;
          custom_domain: string | null;
          last_deployed_at: string | null;
          deployment_status: 'pending' | 'building' | 'ready' | 'error' | null;
          page_views: number;
          unique_visitors: number;
          version: number;
          published_version: number | null;
          created_at: string;
          updated_at: string;
          published_at: string | null;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          name: string;
          slug: string;
          description?: string | null;
          status?: 'draft' | 'published' | 'archived';
          template_id?: string | null;
          components?: any;
          theme?: any;
          seo_metadata?: any;
          deployment_url?: string | null;
          preview_url?: string | null;
          custom_domain?: string | null;
          last_deployed_at?: string | null;
          deployment_status?: 'pending' | 'building' | 'ready' | 'error' | null;
          page_views?: number;
          unique_visitors?: number;
          version?: number;
          published_version?: number | null;
          created_at?: string;
          updated_at?: string;
          published_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          name?: string;
          slug?: string;
          description?: string | null;
          status?: 'draft' | 'published' | 'archived';
          template_id?: string | null;
          components?: any;
          theme?: any;
          seo_metadata?: any;
          deployment_url?: string | null;
          preview_url?: string | null;
          custom_domain?: string | null;
          last_deployed_at?: string | null;
          deployment_status?: 'pending' | 'building' | 'ready' | 'error' | null;
          page_views?: number;
          unique_visitors?: number;
          version?: number;
          published_version?: number | null;
          created_at?: string;
          updated_at?: string;
          published_at?: string | null;
        };
      };
      components: {
        Row: {
          id: string;
          user_id: string | null;
          site_id: string | null;
          name: string;
          type: 'section' | 'element' | 'widget' | 'layout';
          category: string | null;
          definition: any;
          props_schema: any | null;
          default_props: any | null;
          registry_id: string | null;
          variant: string | null;
          registry_metadata: any;
          description: string | null;
          tags: string[] | null;
          is_public: boolean;
          is_ai_generated: boolean;
          is_registry_component: boolean;
          usage_count: number;
          avg_render_time_ms: number;
          lighthouse_score: number;
          accessibility_score: number;
          version: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          site_id?: string | null;
          name: string;
          type: 'section' | 'element' | 'widget' | 'layout';
          category?: string | null;
          definition: any;
          props_schema?: any | null;
          default_props?: any | null;
          registry_id?: string | null;
          variant?: string | null;
          registry_metadata?: any;
          description?: string | null;
          tags?: string[] | null;
          is_public?: boolean;
          is_ai_generated?: boolean;
          is_registry_component?: boolean;
          usage_count?: number;
          avg_render_time_ms?: number;
          lighthouse_score?: number;
          accessibility_score?: number;
          version?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          site_id?: string | null;
          name?: string;
          type?: 'section' | 'element' | 'widget' | 'layout';
          category?: string | null;
          definition?: any;
          props_schema?: any | null;
          default_props?: any | null;
          registry_id?: string | null;
          variant?: string | null;
          registry_metadata?: any;
          description?: string | null;
          tags?: string[] | null;
          is_public?: boolean;
          is_ai_generated?: boolean;
          is_registry_component?: boolean;
          usage_count?: number;
          avg_render_time_ms?: number;
          lighthouse_score?: number;
          accessibility_score?: number;
          version?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      component_selections: {
        Row: {
          id: string;
          site_id: string;
          component_id: string;
          user_id: string | null;
          selection_reason: string | null;
          business_context: any | null;
          user_prompt: string | null;
          model_used: string;
          tokens_used: number;
          selection_confidence: number;
          props_generated: any;
          props_token_count: number;
          render_success: boolean;
          render_time_ms: number | null;
          user_satisfaction_score: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          site_id: string;
          component_id: string;
          user_id?: string | null;
          selection_reason?: string | null;
          business_context?: any | null;
          user_prompt?: string | null;
          model_used: string;
          tokens_used?: number;
          selection_confidence?: number;
          props_generated: any;
          props_token_count?: number;
          render_success?: boolean;
          render_time_ms?: number | null;
          user_satisfaction_score?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          site_id?: string;
          component_id?: string;
          user_id?: string | null;
          selection_reason?: string | null;
          business_context?: any | null;
          user_prompt?: string | null;
          model_used?: string;
          tokens_used?: number;
          selection_confidence?: number;
          props_generated?: any;
          props_token_count?: number;
          render_success?: boolean;
          render_time_ms?: number | null;
          user_satisfaction_score?: number | null;
          created_at?: string;
        };
      };
      templates: {
        Row: {
          id: string;
          name: string;
          slug: string;
          category: 'saas' | 'portfolio' | 'ecommerce' | 'blog' | 'restaurant' | 'landing' | 'other';
          structure: any;
          default_content: any | null;
          theme_presets: any | null;
          ai_prompts: any;
          description: string | null;
          preview_image_url: string | null;
          demo_url: string | null;
          tags: string[] | null;
          features: string[] | null;
          usage_count: number;
          rating: number | null;
          rating_count: number;
          is_premium: boolean;
          price: number | null;
          created_by: string | null;
          is_official: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          category: 'saas' | 'portfolio' | 'ecommerce' | 'blog' | 'restaurant' | 'landing' | 'other';
          structure: any;
          default_content?: any | null;
          theme_presets?: any | null;
          ai_prompts?: any;
          description?: string | null;
          preview_image_url?: string | null;
          demo_url?: string | null;
          tags?: string[] | null;
          features?: string[] | null;
          usage_count?: number;
          rating?: number | null;
          rating_count?: number;
          is_premium?: boolean;
          price?: number | null;
          created_by?: string | null;
          is_official?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          category?: 'saas' | 'portfolio' | 'ecommerce' | 'blog' | 'restaurant' | 'landing' | 'other';
          structure?: any;
          default_content?: any | null;
          theme_presets?: any | null;
          ai_prompts?: any;
          description?: string | null;
          preview_image_url?: string | null;
          demo_url?: string | null;
          tags?: string[] | null;
          features?: string[] | null;
          usage_count?: number;
          rating?: number | null;
          rating_count?: number;
          is_premium?: boolean;
          price?: number | null;
          created_by?: string | null;
          is_official?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      deployments: {
        Row: {
          id: string;
          site_id: string;
          user_id: string | null;
          deployment_id: string | null;
          deployment_url: string | null;
          preview_url: string | null;
          status: 'pending' | 'building' | 'ready' | 'error' | 'cancelled';
          error_message: string | null;
          build_time_seconds: number | null;
          bundle_size_bytes: number | null;
          environment: 'development' | 'preview' | 'production';
          branch: string | null;
          commit_sha: string | null;
          commit_message: string | null;
          metadata: any;
          created_at: string;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          site_id: string;
          user_id?: string | null;
          deployment_id?: string | null;
          deployment_url?: string | null;
          preview_url?: string | null;
          status?: 'pending' | 'building' | 'ready' | 'error' | 'cancelled';
          error_message?: string | null;
          build_time_seconds?: number | null;
          bundle_size_bytes?: number | null;
          environment?: 'development' | 'preview' | 'production';
          branch?: string | null;
          commit_sha?: string | null;
          commit_message?: string | null;
          metadata?: any;
          created_at?: string;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          site_id?: string;
          user_id?: string | null;
          deployment_id?: string | null;
          deployment_url?: string | null;
          preview_url?: string | null;
          status?: 'pending' | 'building' | 'ready' | 'error' | 'cancelled';
          error_message?: string | null;
          build_time_seconds?: number | null;
          bundle_size_bytes?: number | null;
          environment?: 'development' | 'preview' | 'production';
          branch?: string | null;
          commit_sha?: string | null;
          commit_message?: string | null;
          metadata?: any;
          created_at?: string;
          completed_at?: string | null;
        };
      };
      ai_generations: {
        Row: {
          id: string;
          user_id: string | null;
          site_id: string | null;
          generation_type: 'site' | 'component' | 'content' | 'image' | 'optimization';
          prompt: string;
          enhanced_prompt: string | null;
          model: string;
          model_version: string | null;
          input_tokens: number | null;
          output_tokens: number | null;
          total_tokens: number | null;
          estimated_cost: number | null;
          result: any | null;
          success: boolean;
          error_message: string | null;
          duration_ms: number | null;
          metadata: any;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          site_id?: string | null;
          generation_type: 'site' | 'component' | 'content' | 'image' | 'optimization';
          prompt: string;
          enhanced_prompt?: string | null;
          model: string;
          model_version?: string | null;
          input_tokens?: number | null;
          output_tokens?: number | null;
          total_tokens?: number | null;
          estimated_cost?: number | null;
          result?: any | null;
          success?: boolean;
          error_message?: string | null;
          duration_ms?: number | null;
          metadata?: any;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          site_id?: string | null;
          generation_type?: 'site' | 'component' | 'content' | 'image' | 'optimization';
          prompt?: string;
          enhanced_prompt?: string | null;
          model?: string;
          model_version?: string | null;
          input_tokens?: number | null;
          output_tokens?: number | null;
          total_tokens?: number | null;
          estimated_cost?: number | null;
          result?: any | null;
          success?: boolean;
          error_message?: string | null;
          duration_ms?: number | null;
          metadata?: any;
          created_at?: string;
        };
      };
      subscriptions: {
        Row: {
          id: string;
          user_id: string;
          stripe_subscription_id: string | null;
          stripe_customer_id: string | null;
          stripe_price_id: string | null;
          plan: 'free' | 'starter' | 'pro' | 'business';
          status: 'trialing' | 'active' | 'cancelled' | 'incomplete' | 'past_due';
          current_period_start: string | null;
          current_period_end: string | null;
          cancel_at: string | null;
          cancelled_at: string | null;
          monthly_ai_generations: number | null;
          max_sites: number | null;
          max_custom_domains: number | null;
          max_team_members: number | null;
          features: any;
          metadata: any;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          stripe_subscription_id?: string | null;
          stripe_customer_id?: string | null;
          stripe_price_id?: string | null;
          plan: 'free' | 'starter' | 'pro' | 'business';
          status: 'trialing' | 'active' | 'cancelled' | 'incomplete' | 'past_due';
          current_period_start?: string | null;
          current_period_end?: string | null;
          cancel_at?: string | null;
          cancelled_at?: string | null;
          monthly_ai_generations?: number | null;
          max_sites?: number | null;
          max_custom_domains?: number | null;
          max_team_members?: number | null;
          features?: any;
          metadata?: any;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          stripe_subscription_id?: string | null;
          stripe_customer_id?: string | null;
          stripe_price_id?: string | null;
          plan?: 'free' | 'starter' | 'pro' | 'business';
          status?: 'trialing' | 'active' | 'cancelled' | 'incomplete' | 'past_due';
          current_period_start?: string | null;
          current_period_end?: string | null;
          cancel_at?: string | null;
          cancelled_at?: string | null;
          monthly_ai_generations?: number | null;
          max_sites?: number | null;
          max_custom_domains?: number | null;
          max_team_members?: number | null;
          features?: any;
          metadata?: any;
          created_at?: string;
          updated_at?: string;
        };
      };
      assets: {
        Row: {
          id: string;
          user_id: string;
          site_id: string | null;
          file_name: string;
          file_type: string;
          file_size: number;
          url: string;
          alt_text: string | null;
          metadata: any;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          site_id?: string | null;
          file_name: string;
          file_type: string;
          file_size: number;
          url: string;
          alt_text?: string | null;
          metadata?: any;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          site_id?: string | null;
          file_name?: string;
          file_type?: string;
          file_size?: number;
          url?: string;
          alt_text?: string | null;
          metadata?: any;
          created_at?: string;
        };
      };
      analytics_events: {
        Row: {
          id: string;
          site_id: string;
          event_type: string;
          page_path: string | null;
          referrer: string | null;
          user_agent: string | null;
          ip_address: string | null;
          metadata: any;
          created_at: string;
        };
        Insert: {
          id?: string;
          site_id: string;
          event_type: string;
          page_path?: string | null;
          referrer?: string | null;
          user_agent?: string | null;
          ip_address?: string | null;
          metadata?: any;
          created_at?: string;
        };
        Update: {
          id?: string;
          site_id?: string;
          event_type?: string;
          page_path?: string | null;
          referrer?: string | null;
          user_agent?: string | null;
          ip_address?: string | null;
          metadata?: any;
          created_at?: string;
        };
      };
    };
  };
}